name: School-Plugin
version: '1.1.0-SNAPSHOT'
main: com.ryushin.schoolplugin.SchoolPlugin
author: Ryushin 
api-version: '1.21'
commands:
  test:
    description: Perintah admin / test
  menu:
    description: Buka menu konfigurasi sekolah
  kelas:
    description: Manajemen kelas (LuckPerms)
  tugas:
    description: Pengumpulan tugas siswa
  koperasi:
    description: Koperasi / kantin sekolah
  organisasi:
    description: Manajemen organisasi / ekskul
  report:
    description: Manajemen rapor / nilai
