name: School-Plugin
version: '1.1.0-SNAPSHOT'
main: com.ryushin.schoolplugin.SchoolPlugin
author: Ryushin 
api-version: '1.21'
commands:
  test:
    description: Test Command
  panduan:
    description: testing
  kelas:
    description: Kelas Command
  tugas:
    description: Tugas Command
