/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.7.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    
    // Apply the application plugin to add support for building a CLI application in Java.
    id("java")
    id("com.gradleup.shadow") version "8.3.5"
}

group = "com.ryushin"
version = "1.0.0"

repositories {
    mavenLocal()
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")

    implementation("com.ryushin:RyuLib:3.0.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks {
  shadowJar {
    archiveClassifier.set("")
    // relocate("org.sqlite", "com.ryushin.schoolplugin.libs.sqlite")
  }
  build {
    dependsOn(shadowJar)
  }
}
