name: Compile School-Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Root
        uses: actions/checkout@v4
        with:
          path: root

      - name: Checkout RyuLib
        uses: actions/checkout@v4
        with:
          repository: Sahur01-arch/RyuLib
          path: root/RyuLib

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Project
        working-directory: root
        run: ./gradlew build --no-daemon --no-configuration-cache

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: school-plugin-jar
          path: root/School-Plugin/build/libs/*.jar
