name: Compile School-Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and publish RyuLib to local Maven repository
        run: ./gradlew :RyuLib:build :RyuLib:publishToMavenLocal --no-daemon

      - name: Build School-Plugin
        run: ./gradlew :School-Plugin:build --no-daemon --no-configuration-cache
